# This file was generated by GoReleaser. DO NOT EDIT.
cask "stigg" do
  name "stigg"
  desc "The official CLI for Stigg."
  homepage "https://stigg.io"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stigg"
  manpage "man/man1/stigg.1.gz"
  bash_completion "completions/stigg.bash"
  zsh_completion "completions/stigg.zsh"
  fish_completion "completions/stigg.fish"

  on_macos do
    on_intel do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_macos_amd64.zip"
      sha256 "411bc6f4a0488b4e8ba19b5d8d338cc3e7633f14816383fe97e2f073262f6452"
    end
    on_arm do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_macos_arm64.zip"
      sha256 "6073e69789f4eacfe84553767929ea91b03a3e786279f0c3d27e7bab551f1450"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_linux_amd64.tar.gz"
      sha256 "9bf518b10575ae3cb4e5abedf2ba695ca66d38645b3d25eddd934d57bfd6bbcb"
    end
    on_arm do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_linux_arm64.tar.gz"
      sha256 "362f73d39ccdc22875d8fc92b134aa1baacf07e6cf74fad8a49dd0a183bef64c"
    end
  end

  # No zap stanza required
end
