# This file was generated by GoReleaser. DO NOT EDIT.
cask "stigg" do
  name "stigg"
  desc "The official CLI for Stigg."
  homepage "https://stigg.io"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stigg"
  manpage "man/man1/stigg.1.gz"
  bash_completion "completions/stigg.bash"
  zsh_completion "completions/stigg.zsh"
  fish_completion "completions/stigg.fish"

  on_macos do
    on_intel do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_macos_amd64.zip"
      sha256 "5257ba5e89b5d10e3947617bcc238b045842c2f7f342c4b825c4952cc32698ac"
    end
    on_arm do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_macos_arm64.zip"
      sha256 "01a283db5e1dce0e4db134def0790ab93e47323ce773157493e8b74e6dc3d182"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_linux_amd64.tar.gz"
      sha256 "7da951f11bd77b4a74abdaee369f7fcd6a74f23e3acc84b1b86bca3dc13d1f42"
    end
    on_arm do
      url "https://github.com/stiggio/stigg-cli/releases/download/v#{version}/stigg_#{version}_linux_arm64.tar.gz"
      sha256 "1c3834f7009f2edc3a1f0dd4b09358618cd8f910b234433165793937d2726053"
    end
  end

  # No zap stanza required
end
